---
server:
  port: 9081

spring:
  profiles: dev
  application:
    name: springcloud-client-9081


---
server:
  port: 9082

spring:
  profiles: prod
  application:
    name: springcloud-client-9082
